parameters:
    stc_contract.entity.class: Stc\Bundle\ContractBundle\Entity\Contract
    stc_contract.contract.entity.class: Stc\Bundle\ContractBundle\Entity\Contract
    stc_contract.form.type.contract.class: Stc\Bundle\ContractBundle\Form\Type\ContractType
    stc_contract.form.handler.class: Stc\Bundle\ContractBundle\Form\Handler\ContractHandler


services:
    stc.command.entity_update_command:
        class: Stc\Bundle\CommandBundle\Command\EntityUpdateCommand
        tags:
            - { name: console.command }
    stc_contract.form.type.contract:
        class: %stc_contract.form.type.contract.class%
        arguments:
            - %stc_contract.entity.class%
        tags:
            - { name: form.type, alias: stc_contract }
    stc_contract.form.handler:
        class: %stc_contract.form.handler.class%
        scope: request
        arguments:
            - @stc_contract.form
            - @request
            - @doctrine.orm.entity_manager
            - @oro_tag.tag.manager
    stc_contract.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "stc_contract"
            - "stc_contract"
