parameters:
    stc_contract.entity.class: Stc\Bundle\ContractBundle\Entity\Contract
    stc_contract.contract.entity.class: Stc\Bundle\ContractBundle\Entity\Contract
    stc_contract.form.type.contract.class: Stc\Bundle\ContractBundle\Form\Type\ContractType
    stc_contract.form.handler.class: Stc\Bundle\ContractBundle\Form\Handler\ContractHandler
    stc_contract.generator.class: Stc\Bundle\ContractBundle\Model\Generator\ContractGenerator
    stc_contract.generator.variable_model.class: Stc\Bundle\ContractBundle\Model\VariableModel\AbstractVariableModel
    stc_contract.form.type.contract_customizer.class: Stc\Bundle\ContractBundle\Form\Type\ContractCustomizerType

services:
    stc_contract.form.type.contract:
        class: %stc_contract.form.type.contract.class%
        arguments:
            - %stc_contract.entity.class%
        tags:
            - { name: form.type, alias: stc_contract }
    stc_contract.form.handler:
        class: %stc_contract.form.handler.class%
        scope: request
        arguments:
            - @stc_contract.form
            - @request
            - @doctrine.orm.entity_manager
            - @oro_tag.tag.manager
    stc_contract.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "stc_contract"
            - "stc_contract"
    stc_contract.generator:
        class: %stc_contract.generator.class%
        arguments:
            - @twig
    stc_contract.form.builder.contract_customizer:
        class: %stc_contract.form.type.contract_customizer.class%
        tags:
            - { name: form.type, alias: stc_contract_customizer }
