oro_menu_config:
    items:
        map_tab:
            label: Maps
            uri: '#'
        shortcut_map_item:
            label: View Maps
            route: stc_map_index
        shortcut_map_create:
            label: Create Map
            route: stc_map_create
    tree:
        application_menu:
            children:
                map_tab:
                    children:
                        shortcut_map_item: ~
                        shortcut_map_create: ~