stc_map_bundle:
    resource: "@StcMapBundle/Controller/MapController.php"
    type: annotation
    prefix: /map

#stc_map_bundle_api:
#    resource: "@StcMapBundle/Controller/Api/Rest/MapController.php"
#    type: rest
#    prefix: api/rest/{version}/acme
#    requirements:
#        version: latest|v1
#    defaults:
#       version: latest