parameters:
    stc_band.importexport.normalizer.band.class:
        Stc\Bundle\BandBundle\ImportExport\Serializer\Normalizer\BandNormalizer
    stc_band.importexport.strategy.import.band.add_or_replace.class:
        Stc\Bundle\BandBundle\ImportExport\Strategy\Import\AddOrReplaceStrategy
    stc_band.band.entity.class:
        Stc\Bundle\BandBundle\Entity\Band

services:
    stc_band.importexport.strategy.import.band.add_or_replace:
        class: %stc_band.importexport.strategy.import.band.add_or_replace.class%
    stc_band.importexport.normalizer.band:
        class: %stc_band.importexport.normalizer.band.class%
        tags:
            - {name: oro_importexport.normalizer }
    stc_band.importexport.processor.import_band:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setStrategy, [@stc_band.importexport.strategy.import.band.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity:
            %stc_band.band.entity.class%, alias: stc_band.add_or_replace_band }
            - { name: oro_importexport.processor, type: import_validation, entity:
            %stc_band.band.entity.class%, alias: stc_band.add_or_replace_band }